# Generated by Django 5.1.5 on 2025-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_ids',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
